export const users = [
  {
    email: "tony@scos.com",
    password: "Pass@12345",
    name: "Tony Stark",
    institutes: [],
  },
  {
    email: "steve@scos.com", 
    password: "Pass@12345",
    name: "Steve Rogers",
    institutes: [],
  },
  {
    email: "bruce@scos.com",
    password: "Pass@12345",
    name: "Bruce Banner",
    institutes: [
      {
        id: 1,
        name: "North Park Academy",
        location: "Mumbai, Maharashtra",
        type: "School",
        logo: require("../assets/InstituteLogo/Northpark.png"),
        roles: ["Admin"],
      },
    ],
  },
  {
    email: "peter@scos.com",
    password: "Pass@12345",
    name: "Peter Parker",
    institutes: [
      {
        id: 2,
        name: "Earlytech College",
        location: "Pune, Maharashtra",
        type: "College",
        logo: require("../assets/InstituteLogo/EarlyColl.png"),
        roles: ["Admin", "Teacher", "Staff"],
      },
    ],
  },
  {
    email: "natasha@scos.com",
    password: "Pass@12345",
    name: "Natasha Romanoff",
    institutes: [
      {
        id: 1,
        name: "North Park Academy",
        location: "Mumbai, Maharashtra",
        type: "School",
        logo: require("../assets/InstituteLogo/Northpark.png"),
        roles: ["Admin", "Teacher"],
      },
      {
        id: 2,
        name: "Earlytech College",
        location: "Pune, Maharashtra",
        type: "College",
        logo: require("../assets/InstituteLogo/EarlyColl.png"),
        roles: ["Admin", "Staff"],
      },
      {
        id: 3,
        name: "Renaissance Academy",
        location: "Bangalore, Karnataka",
        type: "Training",
        logo: require("../assets/InstituteLogo/Renaissance.png"),
        roles: ["Teacher", "Staff"],
      },
      {
        id: 4,
        name: "Pune University",
        location: "Pune, Maharashtra",
        type: "University",
        logo: require("../assets/InstituteLogo/PuneUniv.png"),
        roles: ["Teacher", "Staff"],
      },
      {
        id: 5,
        name: "Mount Carmel School",
        location: "Nagpur, Maharashtra",
        type: "School",
        logo: require("../assets/InstituteLogo/MoutCarmel.png"),
        roles: ["Admin", "Teacher"],
      },
      {
        id: 6,
        name: "Samhita Academy",
        location: "Chandigarh, Punjab",
        type: "College",
        logo: require("../assets/InstituteLogo/Samhita.png"),
        roles: ["Admin", "Teacher"],
      },
    ],
  },
  {
    email: "thor@scos.com",
    password: "Pass@12345",
    name: "Thor Odinson",
    institutes: [
      {
        id: 1,
        name: "North Park Academy",
        location: "Mumbai, Maharashtra",
        type: "School",
        logo: require("../assets/InstituteLogo/Northpark.png"),
        roles: ["Admin"],
      },
      {
        id: 2,
        name: "Earlytech College",
        location: "Pune, Maharashtra",
        type: "College",
        logo: require("../assets/InstituteLogo/EarlyColl.png"),
        roles: ["Teacher"],
      },
      {
        id: 3,
        name: "Renaissance Academy",
        location: "Bangalore, Karnataka",
        type: "Training",
        logo: require("../assets/InstituteLogo/Renaissance.png"),
        roles: ["Staff"],
      },
    ],
  },
];